name: notebooks
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bs4=4.10.0
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.2
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libpysal=4.5.1
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mgwr=2.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.11
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.4.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - plotly=5.6.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtpy=1.11.2
  - readline=8.1.2
  - requests=2.27.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - soupsieve=2.3.1
  - spglm=1.0.8
  - spreg=1.2.4
  - sqlite=3.37.2
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - click==8.0.4
    - click-plugins==1.1.1
    - cligj==0.7.2
    - fiona==1.8.21
    - geopandas==0.10.2
    - mlxtend==0.19.0
    - munch==2.5.0
    - pyproj==3.3.0
    - shapely==1.8.1.post1
prefix: /Users/Brescia/opt/anaconda3/envs/notebooks
