name: ddust
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - anyio=3.5.0=py39hcbf5309_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb82d6ee_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=22.1.0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - boost-cpp=1.74.0=h5b4e17d_5
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h8ffe710_6
  - brotli-bin=1.0.9=h8ffe710_6
  - brotlipy=0.7.0=py39hb82d6ee_1003
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2022.2.1=haa95532_0
  - cairo=1.16.0=hb19e0ff_1008
  - cdsapi=0.5.1=pyhd8ed1ab_0
  - certifi=2021.10.8=py39haa95532_2
  - cffi=1.15.0=py39h0878f49_0
  - cfitsio=4.0.0=hd67004f_0
  - cftime=1.5.1.1=py39h080aedc_0
  - charset-normalizer=2.0.11=pyhd8ed1ab_0
  - click=8.0.3=py39hcbf5309_1
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.1=py39h7bc7c5c_0
  - curl=7.81.0=h789b8ee_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py39h415ef7b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.12=pyhd3eb1b0_0
  - descartes=1.1.0=pyhd3eb1b0_4
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.2=pyhd8ed1ab_0
  - expat=2.4.4=h39d44d4_0
  - fiona=1.8.20=py39hea8b339_2
  - flit-core=3.6.0=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=h1989441_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py39hb82d6ee_0
  - freetype=2.10.4=h546665d_1
  - freexl=1.0.6=ha8e266a_0
  - fribidi=1.0.10=h8d14728_0
  - gdal=3.3.3=py39h3f5efd6_11
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geos=3.10.1=h39d44d4_1
  - geotiff=1.7.0=hc8731e1_5
  - gettext=0.19.8.1=ha2e2712_1008
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h2a0e4a3_103
  - icu=68.2=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py39hcbf5309_0
  - importlib_metadata=4.10.1=hd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2022.0.0=h57928b3_3663
  - ipykernel=6.8.0=py39h832f523_0
  - ipython=8.0.1=py39hcbf5309_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py39hcbf5309_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hcbf5309_1
  - jupyter_server=1.13.4=pyhd8ed1ab_0
  - jupyterlab=3.2.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kealib=1.4.14=h8995ca9_3
  - kiwisolver=1.3.2=py39h2e07f2f_1
  - krb5=1.19.2=h20d022d_3
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=13_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_6
  - libbrotlidec=1.0.9=h8ffe710_6
  - libbrotlienc=1.0.9=h8ffe710_6
  - libcblas=3.9.0=13_win64_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libcurl=7.81.0=h789b8ee_0
  - libdeflate=1.8=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.3.3=hd873378_11
  - libglib=2.70.2=h3be07f2_1
  - libiconv=1.16=he774522_0
  - libimagequant=2.17.0=hcfcfb64_1
  - libkml=1.3.0=h9859afa_1014
  - liblapack=3.9.0=13_win64_mkl
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libpng=1.6.37=h1d00b33_2
  - libpq=14.1=hfcc5ef8_1
  - librttopo=1.1.0=he35e8ac_8
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=hf126459_12
  - libssh2=1.10.0=h680486a_2
  - libtiff=4.3.0=hd413186_2
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.9.12=hf5bbc77_1
  - libzip=1.8.0=hfed4ece_1
  - libzlib=1.2.11=h8ffe710_1013
  - llvm-openmp=12.0.1=h2d74725_1
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39hb82d6ee_1
  - matplotlib=3.5.1=py39hcbf5309_0
  - matplotlib-base=3.5.1=py39h581301d_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39hb82d6ee_1005
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py39hcbf5309_4
  - nbclassic=0.3.5=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py39hcbf5309_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - netcdf4=1.5.7=py39h3de5c98_1
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.8=pyha770c72_0
  - numpy=1.22.2=py39h6331f09_0
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1m=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - palettable=3.3.0=pyhd3eb1b0_0
  - pandas=1.4.0=py39h2e25243_0
  - pandoc=2.17.1.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py39ha53f419_0
  - pip=22.0.3=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - poppler=21.11.0=h24fffdf_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.1=h1c22c4f_1
  - proj=8.2.0=h1cfcee9_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py39h312c5a8_0
  - pyqt=5.12.3=py39hcbf5309_8
  - pyqt-impl=5.12.3=py39h415ef7b_8
  - pyqt5-sip=4.19.18=py39h415ef7b_8
  - pyqtchart=5.12=py39h415ef7b_8
  - pyqtwebengine=5.12.1=py39h415ef7b_8
  - pyrsistent=0.18.1=py39hb82d6ee_0
  - pysal=2.1.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39hcbf5309_4
  - python=3.9.10=h9a09f29_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pywin32=303=py39hb82d6ee_0
  - pywinpty=2.0.2=py39h99910a6_0
  - pyzmq=22.3.0=py39he46f08e_1
  - qt=5.12.9=h5909a2a_4
  - rasterio=1.2.10=py39h25176d1_2
  - rasterstats=0.16.0=pyhd8ed1ab_0
  - requests=2.27.1=pyhd8ed1ab_0
  - rioxarray=0.9.1=pyhd8ed1ab_0
  - rtree=0.9.7=py39h09fdee3_3
  - scikit-learn=1.0.2=py39he931e04_0
  - scipy=1.7.3=py39hc0c34ad_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.7.1=py39hcbf5309_0
  - shapely=1.8.0=py39h1db6edd_4
  - simplejson=3.17.6=py39hb82d6ee_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py39hcbf5309_2
  - snuggs=1.4.7=py_0
  - sqlite=3.37.0=h8ffe710_0
  - stack_data=0.1.4=pyhd8ed1ab_0
  - tbb=2021.5.0=h2d74725_0
  - terminado=0.13.1=py39hcbf5309_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.5.3=h95dad36_0
  - tk=8.6.11=h8ffe710_1
  - tomli=2.0.0=pyhd8ed1ab_1
  - tornado=6.1=py39hb82d6ee_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py39hb82d6ee_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py39hb82d6ee_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py39haa95532_0
  - win_inet_pton=1.1.0=py39hcbf5309_3
  - winpty=0.4.3=4
  - wrapt=1.13.3=py39h2bbff1b_2
  - xarray=0.21.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h0e60522_4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2022.1.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.2=h6255e5f_0
  - pip:
    - beautifulsoup4==4.10.0
    - blessings==1.7
    - bqplot==0.12.32
    - cachetools==5.0.0
    - colour==0.1.5
    - dill==0.3.4
    - earthengine-api==0.1.297
    - ee==0.2
    - ee-extra==0.0.10
    - ffmpeg-python==0.2.0
    - future==0.18.2
    - geeadd==0.5.5
    - geemap==0.11.4
    - geocoder==1.38.1
    - geojson==2.5.0
    - google-api-core==2.5.0
    - google-api-python-client==1.12.10
    - google-auth==2.6.0
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.2.2
    - google-cloud-storage==2.1.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.1.0
    - googleapis-common-protos==1.54.0
    - googledrivedownloader==0.4
    - here-map-widget-for-jupyter==1.1.3
    - httplib2==0.20.4
    - httplib2shim==0.0.3
    - ipyevents==2.0.1
    - ipyfilechooser==0.6.0
    - ipyleaflet==0.15.0
    - ipynb-py-convert==0.4.6
    - ipytree==0.2.1
    - jupyterlab-widgets==1.0.2
    - logzero==1.7.0
    - mss==6.1.0
    - openturns==1.18
    - owslib==0.25.0
    - plotly==5.5.0
    - protobuf==3.19.4
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycrs==1.0.2
    - pykrige==1.6.1
    - pyshp==2.2.0
    - python-box==5.4.1
    - pyyaml==6.0
    - ratelim==0.1.6
    - rsa==4.8
    - sankee==0.0.7
    - sodapy==2.1.0
    - soupsieve==2.3.1
    - tenacity==8.0.1
    - tifffile==2022.2.9
    - traittypes==0.2.1
    - uritemplate==3.0.1
    - voila==0.3.1
    - watermark==2.3.0
    - websockets==10.1
    - whitebox==2.1.1
    - whiteboxgui==0.7.0
prefix: C:\Users\Administrator\anaconda3\envs\ddust
